/*
 * fir_test_application.c
 *
 *  Created on: 09-Mar-2012
 *  updated on: 13-Aug-2013
 *      Author: Sudheer
 */

#include <stdio.h>
#include "xparameters.h"
#include "xfir_hw.h"
#include "xparameters.h"
#include "xfir.h"
#include "xil_printf.h"

void FIR_ISR(void *InstancePtr);
XFir fir_hw;
extern XFir fir_hw;
volatile static int NewResult = 0;

XFir_Config fir_config = {
		0,
		XPAR_FIR_0_S_AXI_FIR_IO_BASEADDR
};

int FirSetup(){
    //Initialize the FIR IP block generated by Vivado HLS
	return XFir_Initialize(&fir_hw,XPAR_FIR_0_DEVICE_ID);
}

void FirStart(void *InstancePtr){
	XFir *pFir = (XFir *)InstancePtr;
	
	//Enable the local interrupt
	XFir_InterruptEnable(pFir,1);
	
	//Enable the global interrupt (GIE)
	XFir_InterruptGlobalEnable(pFir);
	
	//Start the FIR core
	XFir_Start(pFir);
}

void FIR_ISR(void *InstancePtr){
	print("ISR routine");
	XFir *pFir = (XFir *)InstancePtr;

	//Disable the GIE from the adder
	XFir_InterruptGlobalDisable(pFir);
	//Disable the local interrupt
	XFir_InterruptDisable(pFir,0xffffffff);

	// clear the local interrupt
	XFir_InterruptClear(pFir,1);

    //Set the flag to mark a new result was received
	NewResult = 1;
	// restart the core if it should run again

}

int main()
{

    int i;
    const int SAMPLES = 11;
    int output_array[11];
    int ref_output[11] = {0,-10,-9,23,56,63,56,23,-9,-10,0}; // Filter Coefficients; used to test against filter output for impulse input sequence
    int err_count = 0;
    int y_valid_status =0;

    print("FIR Application Test\r\n");
    print("====================\r\n");
    int status;
    //Setup the Adder core
    status = FirSetup();
    if(status != XST_SUCCESS){
    	print("FIR Setup Failed\r\n");
    }else{
    	print("FIR Setup Successful\r\n");
    }

    for (i=0;i<SAMPLES;i++)
    {
    	if (i==0)
    		XFir_Set_x(&fir_hw, 1);
    	else
    		XFir_Set_x(&fir_hw, 0);

    	//Launch the FIR
    	XFir_Start(&fir_hw);

    	while (!y_valid_status){
    		y_valid_status = XFir_Get_y_vld(&fir_hw);
    	}

    	output_array[i] = XFir_Get_y(&fir_hw);
    	y_valid_status = 0;

    	NewResult = 0;

    	//Get the result values from the FIR core
    	output_array[i] = XFir_Get_y(&fir_hw);
    	//xil_printf("HW Output Value = %d, Expected Output Value = %d \n",output_array[i],ref_output[i]);

    	if (ref_output[i] == output_array[i])
    		err_count = err_count ;
    	else
    		err_count = err_count + 1;
    }

    if (err_count == 0)
    	print ("Impulse response test passed\r\n");
    else
    	print ("Impulse response test failed\r\n");

    return 0;
}







