-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
-- Version: 2022.2
-- Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity adder is
port (
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    A : IN STD_LOGIC_VECTOR (1 downto 0);
    B : IN STD_LOGIC_VECTOR (1 downto 0);
    Cin : IN STD_LOGIC_VECTOR (1 downto 0);
    ap_return : OUT STD_LOGIC_VECTOR (2 downto 0) );
end;


architecture behav of adder is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "adder_adder,hls_ip_2022_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg484-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=2.693000,HLS_SYN_LAT=0,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=0,HLS_SYN_LUT=8,HLS_VERSION=2022_2}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_const_boolean_1 : BOOLEAN := true;

    signal sext_ln186_fu_44_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal sext_ln6_fu_52_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal add_ln6_1_fu_56_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal sext_ln186_1_fu_48_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_ce_reg : STD_LOGIC;


begin



    add_ln6_1_fu_56_p2 <= std_logic_vector(signed(sext_ln186_fu_44_p1) + signed(sext_ln6_fu_52_p1));
    ap_done <= ap_start;
    ap_idle <= ap_const_logic_1;
    ap_ready <= ap_start;
    ap_return <= std_logic_vector(unsigned(add_ln6_1_fu_56_p2) + unsigned(sext_ln186_1_fu_48_p1));
        sext_ln186_1_fu_48_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(B),3));

        sext_ln186_fu_44_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(A),3));

        sext_ln6_fu_52_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(Cin),3));

end behav;
